# fly.toml app configuration file generated for travel-diary-api on 2023-05-04T13:38:31+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "travel-diary-api"
primary_region = "waw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
